### PR TITLE
adds amd builds

### PR DESCRIPTION
**Pull request by mikenomitch**
using require.js with my branch I was able to get this build working

questions:
  - anything you want added to the config?
  - should the maps be included?

### CODE REVIEW

**Comment by aaronshaf** [comment]
+1

@brentburg, thoughts?

**Comment by aaronshaf** [comment]
@brentburg, I am going to merge this today if you don't have any objections

**Comment by brentburg** [comment]
:+1: Looks good to me.

**Comment by brentburg** [comment]
Published to npm (v0.3.1)

**Pull request merged**
